# Generated by Django 4.0.3 on 2022-03-22 05:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gear.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SmallIntegerField(choices=[(1, 'customer name - note')], verbose_name='Notification Identification Code')),
                ('note', models.CharField(max_length=300, verbose_name='Note')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=30, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('schedule', models.CharField(max_length=20)),
                ('last_run', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_run_status', models.BooleanField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('onapproach', models.CharField(default=gear.models.onapproachmessage, max_length=500, verbose_name='On Approach Message Body')),
                ('smsreminder', models.CharField(default=gear.models.smsreminder, max_length=500, verbose_name='SMS Reminder Message Body')),
                ('smsreminder_status', models.BooleanField(default=False, verbose_name='status')),
                ('smsreminder_cron', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cron Comment')),
                ('smsreminder_time', models.TimeField(default=datetime.time(17, 0), verbose_name='SMS reminder scheduled time')),
                ('selfsignupsms', models.CharField(default=gear.models.selfsignupsms, max_length=500, verbose_name='Self Signup Message Body')),
                ('customers_visability', models.BooleanField(default=False, verbose_name='sharing admin Customers with employees Accounts')),
                ('appointments_visability', models.BooleanField(default=False, verbose_name='sharing admin appointments with employees Accounts')),
                ('invoices_visability', models.BooleanField(default=False, verbose_name='sharing admin Invoices with employees Accounts')),
                ('productslist_visability', models.BooleanField(default=False, verbose_name='sharing admin products list with employees Accounts')),
                ('productslist_accessability', models.BooleanField(default=False, verbose_name='allowing admin to see all created products list')),
                ('initial_invoice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Invoice Starting Number')),
                ('quotesms_notification', models.BooleanField(default=False, verbose_name='Quote SMS Notificaiton')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminConfigurations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('under_30_discount', models.DecimalField(decimal_places=2, default=18.5, max_digits=6, verbose_name='Sub Total')),
                ('over_30_discount', models.DecimalField(decimal_places=2, default=22.5, max_digits=6, verbose_name='Sub Total')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_conf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
