# Generated by Django 4.0.3 on 2022-03-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='code',
            field=models.SmallIntegerField(choices=[(1, 'customer name - note'), (2, 'Subscription Error - Note')], verbose_name='Notification Identification Code'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
