# Generated by Django 4.0.3 on 2022-03-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_alter_notifications_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='code',
            field=models.SmallIntegerField(choices=[(1, 'customer name - note'), (2, 'Subscription Limit Reached')], verbose_name='Notification Identification Code'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_days', models.CharField(default='[1,2,3,4,5,6]', max_length=30, verbose_name='List of workdays')),
                ('start_time', models.TimeField(default='07:00', verbose_name='Start Time')),
                ('end_time', models.TimeField(default='18:00', verbose_name='End Time')),
                ('first_day', models.CharField(default='1', max_length=30, verbose_name='First day of the week')),
                ('slot_duration', models.CharField(default='00:30', max_length=30, verbose_name='Slot Duration')),
                ('configurations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='gear.configurations')),
            ],
        ),
    ]
