# Generated by Django 4.0.3 on 2022-03-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_alter_notifications_code_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='invoice_note',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Invoice footer Note'),
        ),
    ]
