# Generated by Django 4.0.3 on 2022-03-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_configurations_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='work_days',
            field=models.CharField(default="['1','2','3','4','5','6']", max_length=40, verbose_name='List of workdays'),
        ),
    ]
