# Generated by Django 4.0.3 on 2022-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_alter_calendar_work_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='invoice_footer',
            field=models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='Invoice footer'),
        ),
    ]
