# Generated by Django 4.0.3 on 2022-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_calendar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='can_save_attachments',
            field=models.BooleanField(default=True),
        ),
    ]
