# Generated by Django 4.0.3 on 2022-03-22 05:58

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='full name')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='Mobile number')),
                ('color', models.CharField(blank=True, default='#0000ff', max_length=30, null=True, verbose_name='Calendar Color')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('terms_conditions', models.BooleanField(default=False, verbose_name='Terms and Conditions')),
                ('privacy_policy', models.BooleanField(default=False, verbose_name='Privacy Policy')),
                ('is_parent', models.BooleanField(default=False)),
                ('auth_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Mobile Authentication Code')),
                ('code_attempts', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Incorrect Attempts')),
                ('auth_code_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=True)),
                ('profile_img', models.ImageField(default=account.models.default_profile_img, upload_to=account.models.profile_img_path)),
                ('hide_email', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('job_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Job Title')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, verbose_name='Receiver Number')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('status', models.BooleanField(default=False, verbose_name='Message Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smslog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Business Name')),
                ('abn', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Business ABN')),
                ('gst_registered', models.BooleanField(default=False, verbose_name='GST Registered')),
                ('logo', models.ImageField(default=account.models.default_logo_img, upload_to=account.models.business_logo_path)),
                ('bsb', models.CharField(default='', max_length=10, verbose_name='BSB')),
                ('account_number', models.CharField(default='', max_length=14, verbose_name='Account Number')),
                ('account_name', models.CharField(default='', max_length=100, verbose_name='Account Name')),
                ('bank_name', models.CharField(default='', max_length=50, verbose_name='Bank Name')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('house_no', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='street')),
                ('suburb', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='suburb')),
                ('postcode', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='postcode')),
                ('state', models.CharField(blank=True, choices=[('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], default='', max_length=30, null=True, verbose_name='state')),
                ('country', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Country')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
                ('business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.business')),
            ],
        ),
    ]
