# Generated by Django 4.0.3 on 2022-04-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_can_save_attachments_business_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='can_save_attachments',
        ),
    ]
