# Generated by Django 4.0.3 on 2022-04-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emergencycontact_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperFund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(default='', max_length=120, verbose_name='Fund Name')),
                ('product_code', models.CharField(default='', max_length=30, verbose_name='Product Code')),
                ('member_number', models.CharField(default='', max_length=25, verbose_name='Member Number')),
                ('pay_to_fund', models.BooleanField(default=True, verbose_name='Pay to this Fund')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
