# Generated by Django 4.0.3 on 2022-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_superfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfund',
            name='pay_to_fund',
            field=models.BooleanField(default=False, verbose_name='Pay to this Fund'),
        ),
    ]
