# Generated by Django 4.0.3 on 2022-04-14 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_superfund_pay_to_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econtact', to=settings.AUTH_USER_MODEL),
        ),
    ]
