# Generated by Django 4.0.3 on 2022-04-16 05:04

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_emergencycontact_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=120, verbose_name='License Name')),
                ('file', models.FileField(upload_to=account.models.licenses_file_path)),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('filesize', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='File Size')),
                ('obtained_date', models.DateField(blank=True, null=True, verbose_name='Obtained Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Attached')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
