# Generated by Django 4.0.3 on 2022-04-16 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_l_name_licenses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenses',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
