# Generated by Django 4.0.3 on 2022-04-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_tfd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfd',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tfd', to=settings.AUTH_USER_MODEL),
        ),
    ]
