# Generated by Django 4.0.3 on 2022-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_tfd_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfd',
            name='medicare_levy',
            field=models.CharField(default='tfd_medicare_levy_0', max_length=40, verbose_name='Medicare Levy Exemption'),
        ),
    ]
