# Generated by Django 4.0.3 on 2022-03-22 05:54

import customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last name')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Full name')),
                ('number', models.CharField(max_length=16, verbose_name='Mobile number')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Address')),
                ('business_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Business Name')),
                ('business_abn', models.CharField(blank=True, max_length=20, null=True, verbose_name='Business ABN')),
                ('terms_conditions', models.BooleanField(default=False, verbose_name='Terms and Conditions')),
                ('privacy_policy', models.BooleanField(default=False, verbose_name='Privacy Policy')),
                ('is_active', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=True)),
                ('hide_email', models.BooleanField(default=True)),
                ('show_attachments', models.BooleanField(default=False, verbose_name='Show Attachments on Profile')),
                ('public_link', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Public Link')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcustomers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(max_length=500, verbose_name='Note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cus_SelfSignupCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_self_signup_code', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cus_Attachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=customer.models.file_path)),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('filesize', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='File Size')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Attached')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customer.customer')),
            ],
        ),
    ]
