# Generated by Django 4.0.3 on 2022-03-22 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subscription.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=300, verbose_name='Access Token')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Obtained')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_id', models.CharField(max_length=120, verbose_name='Product Id')),
                ('plan_id', models.CharField(max_length=120, verbose_name='Plan Id')),
                ('name', models.CharField(max_length=120, verbose_name='Plan Name')),
                ('description', models.CharField(max_length=220, verbose_name='Plan Description')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('INACTIVE', 'INACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=20, verbose_name='Plan Status')),
                ('frequency_unit', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], default='MONTH', max_length=20, verbose_name='Frequency')),
                ('frequency_count', models.SmallIntegerField(default=1, verbose_name='Frequency Count')),
                ('sequence', models.SmallIntegerField(default=1, verbose_name='Sequence')),
                ('payment_failure_threshold', models.SmallIntegerField(default=0, verbose_name='payment_failure_threshold')),
                ('fixed_price_value', models.CharField(max_length=8, verbose_name='Fixed Price Value')),
                ('fixed_price_currency', models.CharField(default='AUD', max_length=10, verbose_name='Currency')),
                ('tenure_type', models.CharField(choices=[('TRIAL', 'TRIAL'), ('REGULAR', 'REGULAR')], default='REGULAR', max_length=8, verbose_name='Tenure type')),
                ('tax_rate', models.CharField(default=10, max_length=8, verbose_name='Fixed Price Value')),
                ('tax_inclusive', models.BooleanField(default=True)),
                ('allowed_sms', models.SmallIntegerField(default=100, verbose_name='Allowed SMSs')),
                ('allowed_accounts', models.SmallIntegerField(default=1, verbose_name='Allowed Number Accounts')),
                ('allowed_storage', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Allowed Storage Space')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('Trial', 'Trial'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Custom', 'Custom')], default='Trial', max_length=120, verbose_name='Subscription Level')),
                ('used_accounts', models.SmallIntegerField(default=1, verbose_name='Used Account')),
                ('used_sms', models.SmallIntegerField(default=0, verbose_name='Used SMSs')),
                ('used_storage', models.SmallIntegerField(default=0, verbose_name='Used Storage Space')),
                ('status', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, default=subscription.models.one_week_later, null=True, verbose_name='Expiry Date')),
                ('pending_subscription', models.CharField(blank=True, max_length=120, null=True)),
                ('active_subscription', models.CharField(blank=True, max_length=120, null=True)),
                ('cancelled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelled')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='subscription.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SubHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_status', models.CharField(blank=True, max_length=120, null=True, verbose_name='Status')),
                ('sub_id', models.CharField(max_length=120)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment amount')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Outstanding Balance')),
                ('total_cycles', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Number of Cycles')),
                ('failed_payments_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Number of Cycles')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Next Billing Date')),
                ('plan', models.CharField(blank=True, max_length=120, null=True, verbose_name='Plan Name')),
                ('payer_id', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Subscriber Email')),
                ('payer_first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_street', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_city', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_state', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_postcode', models.CharField(blank=True, max_length=60, null=True)),
                ('payer_country', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_history', to='subscription.subscription')),
            ],
        ),
    ]
