# Generated by Django 4.0.3 on 2022-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subhistory',
            name='plan',
        ),
        migrations.AlterField(
            model_name='subhistory',
            name='sub_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
