# Generated by Django 4.0.3 on 2022-03-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subhistory_plan_alter_subhistory_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subhistory',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_history', to='subscription.plan'),
        ),
    ]
