# Generated by Django 4.0.3 on 2022-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subhistory_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subhistory',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Parent ID'),
        ),
    ]
