# Generated by Django 4.0.3 on 2022-03-29 14:01

from django.db import migrations, models
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subhistory_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, default=subscription.models.four_weeks_later, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='used_storage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Used Storage Space'),
        ),
    ]
