# Generated by Django 4.0.3 on 2022-03-30 17:12

from django.db import migrations, models
import subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, default=subscription.models.thirty_days_later, null=True, verbose_name='Expiry Date'),
        ),
    ]
