# Generated by Django 4.0.3 on 2022-03-22 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoicing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Quote', 'Quote'), ('Invoice', 'Invoice')], max_length=20, verbose_name='Title')),
                ('invoice_no', models.CharField(blank=True, max_length=4, null=True, verbose_name='Invoice Number')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Sub Total')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total Value')),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total GST')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount Received')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Balance Due')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CASH_ON_DELIVERY', 'Cash On Delivery'), ('EFTPOS', 'EFTPOS'), ('PAYPAL', 'PAYPAL')], max_length=30, verbose_name='Payment Method')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
                ('invoice_date', models.DateField(verbose_name='Invoice Created')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('show_attachments', models.BooleanField(default=False, verbose_name='Show Attachments on Invoice')),
                ('public_link', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Public Link')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.customer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=16)),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.BooleanField(blank=True, max_length=10, null=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_status', to='invoicing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200, verbose_name='Product Title')),
                ('product_description', models.CharField(max_length=500, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productslist', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_productslist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Title')),
                ('product_description', models.CharField(max_length=500, verbose_name='Product Description')),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoicing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('update', models.CharField(max_length=200, verbose_name='Update Notes')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='invoicing.invoice')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=invoicing.models.file_path)),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('filesize', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='File Size')),
                ('public_link', models.CharField(blank=True, max_length=120, null=True, verbose_name='Public Link')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Attached')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoicing.invoice')),
            ],
        ),
    ]
